trigger:
- main 
pool:
  name: maquinapessoal  

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true
    architecture: 'x64'
  

- script: |
    pip install -r requirements.txt
  displayName: 'Instalar dependências do Robot Framework'

- script: |
    python config.py  
  displayName: 'Executar testes Robot Framework'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.xml'  
    testRunTitle: 'Resultados dos testes Robot Framework'
    mergeTestResults: true
