trigger:
- main 
pool:
  name: maquinapessoal  

steps:

- script: |
    pip install -r requirements.txt
  displayName: 'Instalar dependências do Robot Framework'

- script: |
    python config.py  
  displayName: 'Executar testes Robot Framework'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.xml'  
    testRunTitle: 'Resultados dos testes Robot Framework'
    mergeTestResults: true
